package zhentao.zhang.pojo;

import java.util.Date;

public class Collection {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column collection.coll_id
     *
     * @mbggenerated
     */
    private Integer collId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column collection.user_id
     *
     * @mbggenerated
     */
    private Integer userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column collection.post_id
     *
     * @mbggenerated
     */
    private Integer postId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column collection.coll_time
     *
     * @mbggenerated
     */
    private Date collTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column collection.note
     *
     * @mbggenerated
     */
    private String note;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column collection.is_delete
     *
     * @mbggenerated
     */
    private Boolean isDelete;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column collection.create_time
     *
     * @mbggenerated
     */
    private Date createTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column collection.coll_id
     *
     * @return the value of collection.coll_id
     *
     * @mbggenerated
     */
    public Integer getCollId() {
        return collId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column collection.coll_id
     *
     * @param collId the value for collection.coll_id
     *
     * @mbggenerated
     */
    public void setCollId(Integer collId) {
        this.collId = collId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column collection.user_id
     *
     * @return the value of collection.user_id
     *
     * @mbggenerated
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column collection.user_id
     *
     * @param userId the value for collection.user_id
     *
     * @mbggenerated
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column collection.post_id
     *
     * @return the value of collection.post_id
     *
     * @mbggenerated
     */
    public Integer getPostId() {
        return postId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column collection.post_id
     *
     * @param postId the value for collection.post_id
     *
     * @mbggenerated
     */
    public void setPostId(Integer postId) {
        this.postId = postId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column collection.coll_time
     *
     * @return the value of collection.coll_time
     *
     * @mbggenerated
     */
    public Date getCollTime() {
        return collTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column collection.coll_time
     *
     * @param collTime the value for collection.coll_time
     *
     * @mbggenerated
     */
    public void setCollTime(Date collTime) {
        this.collTime = collTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column collection.note
     *
     * @return the value of collection.note
     *
     * @mbggenerated
     */
    public String getNote() {
        return note;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column collection.note
     *
     * @param note the value for collection.note
     *
     * @mbggenerated
     */
    public void setNote(String note) {
        this.note = note == null ? null : note.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column collection.is_delete
     *
     * @return the value of collection.is_delete
     *
     * @mbggenerated
     */
    public Boolean getIsDelete() {
        return isDelete;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column collection.is_delete
     *
     * @param isDelete the value for collection.is_delete
     *
     * @mbggenerated
     */
    public void setIsDelete(Boolean isDelete) {
        this.isDelete = isDelete;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column collection.create_time
     *
     * @return the value of collection.create_time
     *
     * @mbggenerated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column collection.create_time
     *
     * @param createTime the value for collection.create_time
     *
     * @mbggenerated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }
}