package zhentao.zhang.pojo;

import java.util.Date;

public class Collection {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cux_todo_items.todo_item_id
     *
     * @mbggenerated
     */
    private Integer todoItemId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cux_todo_items.user_id
     *
     * @mbggenerated
     */
    private Integer userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cux_todo_items.todo_item_title
     *
     * @mbggenerated
     */
    private String todoItemTitle;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cux_todo_items.todo_item_content
     *
     * @mbggenerated
     */
    private String todoItemContent;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cux_todo_items.priority
     *
     * @mbggenerated
     */
    private String priority;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cux_todo_items.creation_date
     *
     * @mbggenerated
     */
    private Date creationDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cux_todo_items.last_update_date
     *
     * @mbggenerated
     */
    private Date lastUpdateDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cux_todo_items.comments
     *
     * @mbggenerated
     */
    private String comments;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cux_todo_items.todo_item_id
     *
     * @return the value of cux_todo_items.todo_item_id
     *
     * @mbggenerated
     */
    public Integer getTodoItemId() {
        return todoItemId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cux_todo_items.todo_item_id
     *
     * @param todoItemId the value for cux_todo_items.todo_item_id
     *
     * @mbggenerated
     */
    public void setTodoItemId(Integer todoItemId) {
        this.todoItemId = todoItemId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cux_todo_items.user_id
     *
     * @return the value of cux_todo_items.user_id
     *
     * @mbggenerated
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cux_todo_items.user_id
     *
     * @param userId the value for cux_todo_items.user_id
     *
     * @mbggenerated
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cux_todo_items.todo_item_title
     *
     * @return the value of cux_todo_items.todo_item_title
     *
     * @mbggenerated
     */
    public String getTodoItemTitle() {
        return todoItemTitle;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cux_todo_items.todo_item_title
     *
     * @param todoItemTitle the value for cux_todo_items.todo_item_title
     *
     * @mbggenerated
     */
    public void setTodoItemTitle(String todoItemTitle) {
        this.todoItemTitle = todoItemTitle == null ? null : todoItemTitle.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cux_todo_items.todo_item_content
     *
     * @return the value of cux_todo_items.todo_item_content
     *
     * @mbggenerated
     */
    public String getTodoItemContent() {
        return todoItemContent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cux_todo_items.todo_item_content
     *
     * @param todoItemContent the value for cux_todo_items.todo_item_content
     *
     * @mbggenerated
     */
    public void setTodoItemContent(String todoItemContent) {
        this.todoItemContent = todoItemContent == null ? null : todoItemContent.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cux_todo_items.priority
     *
     * @return the value of cux_todo_items.priority
     *
     * @mbggenerated
     */
    public String getPriority() {
        return priority;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cux_todo_items.priority
     *
     * @param priority the value for cux_todo_items.priority
     *
     * @mbggenerated
     */
    public void setPriority(String priority) {
        this.priority = priority == null ? null : priority.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cux_todo_items.creation_date
     *
     * @return the value of cux_todo_items.creation_date
     *
     * @mbggenerated
     */
    public Date getCreationDate() {
        return creationDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cux_todo_items.creation_date
     *
     * @param creationDate the value for cux_todo_items.creation_date
     *
     * @mbggenerated
     */
    public void setCreationDate(Date creationDate) {
        this.creationDate = creationDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cux_todo_items.last_update_date
     *
     * @return the value of cux_todo_items.last_update_date
     *
     * @mbggenerated
     */
    public Date getLastUpdateDate() {
        return lastUpdateDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cux_todo_items.last_update_date
     *
     * @param lastUpdateDate the value for cux_todo_items.last_update_date
     *
     * @mbggenerated
     */
    public void setLastUpdateDate(Date lastUpdateDate) {
        this.lastUpdateDate = lastUpdateDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cux_todo_items.comments
     *
     * @return the value of cux_todo_items.comments
     *
     * @mbggenerated
     */
    public String getComments() {
        return comments;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cux_todo_items.comments
     *
     * @param comments the value for cux_todo_items.comments
     *
     * @mbggenerated
     */
    public void setComments(String comments) {
        this.comments = comments == null ? null : comments.trim();
    }
}