package zhentao.zhang.pojo;

import java.util.Date;

public class Friend {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column friend.fri_id
     *
     * @mbggenerated
     */
    private Integer friId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column friend.from_id
     *
     * @mbggenerated
     */
    private Integer fromId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column friend.to_id
     *
     * @mbggenerated
     */
    private Integer toId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column friend.create_time
     *
     * @mbggenerated
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column friend.is_delete
     *
     * @mbggenerated
     */
    private Boolean isDelete;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column friend.note
     *
     * @mbggenerated
     */
    private String note;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column friend.fri_id
     *
     * @return the value of friend.fri_id
     *
     * @mbggenerated
     */
    public Integer getFriId() {
        return friId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column friend.fri_id
     *
     * @param friId the value for friend.fri_id
     *
     * @mbggenerated
     */
    public void setFriId(Integer friId) {
        this.friId = friId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column friend.from_id
     *
     * @return the value of friend.from_id
     *
     * @mbggenerated
     */
    public Integer getFromId() {
        return fromId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column friend.from_id
     *
     * @param fromId the value for friend.from_id
     *
     * @mbggenerated
     */
    public void setFromId(Integer fromId) {
        this.fromId = fromId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column friend.to_id
     *
     * @return the value of friend.to_id
     *
     * @mbggenerated
     */
    public Integer getToId() {
        return toId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column friend.to_id
     *
     * @param toId the value for friend.to_id
     *
     * @mbggenerated
     */
    public void setToId(Integer toId) {
        this.toId = toId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column friend.create_time
     *
     * @return the value of friend.create_time
     *
     * @mbggenerated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column friend.create_time
     *
     * @param createTime the value for friend.create_time
     *
     * @mbggenerated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column friend.is_delete
     *
     * @return the value of friend.is_delete
     *
     * @mbggenerated
     */
    public Boolean getIsDelete() {
        return isDelete;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column friend.is_delete
     *
     * @param isDelete the value for friend.is_delete
     *
     * @mbggenerated
     */
    public void setIsDelete(Boolean isDelete) {
        this.isDelete = isDelete;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column friend.note
     *
     * @return the value of friend.note
     *
     * @mbggenerated
     */
    public String getNote() {
        return note;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column friend.note
     *
     * @param note the value for friend.note
     *
     * @mbggenerated
     */
    public void setNote(String note) {
        this.note = note == null ? null : note.trim();
    }
}