package zhentao.zhang.pojo;

import java.util.Date;

public class GameReservation {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column game_reservation.game_res_id
     *
     * @mbggenerated
     */
    private Integer gameResId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column game_reservation.player_id
     *
     * @mbggenerated
     */
    private Integer playerId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column game_reservation.game_time
     *
     * @mbggenerated
     */
    private Date gameTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column game_reservation.address
     *
     * @mbggenerated
     */
    private String address;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column game_reservation.team
     *
     * @mbggenerated
     */
    private String team;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column game_reservation.level
     *
     * @mbggenerated
     */
    private String level;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column game_reservation.note
     *
     * @mbggenerated
     */
    private String note;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column game_reservation.is_receive
     *
     * @mbggenerated
     */
    private Boolean isReceive;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column game_reservation.is_delete
     *
     * @mbggenerated
     */
    private Boolean isDelete;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column game_reservation.create_time
     *
     * @mbggenerated
     */
    private Date createTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column game_reservation.game_res_id
     *
     * @return the value of game_reservation.game_res_id
     *
     * @mbggenerated
     */
    public Integer getGameResId() {
        return gameResId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column game_reservation.game_res_id
     *
     * @param gameResId the value for game_reservation.game_res_id
     *
     * @mbggenerated
     */
    public void setGameResId(Integer gameResId) {
        this.gameResId = gameResId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column game_reservation.player_id
     *
     * @return the value of game_reservation.player_id
     *
     * @mbggenerated
     */
    public Integer getPlayerId() {
        return playerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column game_reservation.player_id
     *
     * @param playerId the value for game_reservation.player_id
     *
     * @mbggenerated
     */
    public void setPlayerId(Integer playerId) {
        this.playerId = playerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column game_reservation.game_time
     *
     * @return the value of game_reservation.game_time
     *
     * @mbggenerated
     */
    public Date getGameTime() {
        return gameTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column game_reservation.game_time
     *
     * @param gameTime the value for game_reservation.game_time
     *
     * @mbggenerated
     */
    public void setGameTime(Date gameTime) {
        this.gameTime = gameTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column game_reservation.address
     *
     * @return the value of game_reservation.address
     *
     * @mbggenerated
     */
    public String getAddress() {
        return address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column game_reservation.address
     *
     * @param address the value for game_reservation.address
     *
     * @mbggenerated
     */
    public void setAddress(String address) {
        this.address = address == null ? null : address.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column game_reservation.team
     *
     * @return the value of game_reservation.team
     *
     * @mbggenerated
     */
    public String getTeam() {
        return team;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column game_reservation.team
     *
     * @param team the value for game_reservation.team
     *
     * @mbggenerated
     */
    public void setTeam(String team) {
        this.team = team == null ? null : team.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column game_reservation.level
     *
     * @return the value of game_reservation.level
     *
     * @mbggenerated
     */
    public String getLevel() {
        return level;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column game_reservation.level
     *
     * @param level the value for game_reservation.level
     *
     * @mbggenerated
     */
    public void setLevel(String level) {
        this.level = level == null ? null : level.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column game_reservation.note
     *
     * @return the value of game_reservation.note
     *
     * @mbggenerated
     */
    public String getNote() {
        return note;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column game_reservation.note
     *
     * @param note the value for game_reservation.note
     *
     * @mbggenerated
     */
    public void setNote(String note) {
        this.note = note == null ? null : note.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column game_reservation.is_receive
     *
     * @return the value of game_reservation.is_receive
     *
     * @mbggenerated
     */
    public Boolean getIsReceive() {
        return isReceive;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column game_reservation.is_receive
     *
     * @param isReceive the value for game_reservation.is_receive
     *
     * @mbggenerated
     */
    public void setIsReceive(Boolean isReceive) {
        this.isReceive = isReceive;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column game_reservation.is_delete
     *
     * @return the value of game_reservation.is_delete
     *
     * @mbggenerated
     */
    public Boolean getIsDelete() {
        return isDelete;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column game_reservation.is_delete
     *
     * @param isDelete the value for game_reservation.is_delete
     *
     * @mbggenerated
     */
    public void setIsDelete(Boolean isDelete) {
        this.isDelete = isDelete;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column game_reservation.create_time
     *
     * @return the value of game_reservation.create_time
     *
     * @mbggenerated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column game_reservation.create_time
     *
     * @param createTime the value for game_reservation.create_time
     *
     * @mbggenerated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }
}