package zhentao.zhang.pojo;

import java.util.Date;

public class GameReply {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column game_reply.game_rep_id
     *
     * @mbggenerated
     */
    private Integer gameRepId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column game_reply.player_id
     *
     * @mbggenerated
     */
    private Integer playerId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column game_reply.game_res_id
     *
     * @mbggenerated
     */
    private Integer gameResId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column game_reply.status
     *
     * @mbggenerated
     */
    private String status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column game_reply.note
     *
     * @mbggenerated
     */
    private String note;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column game_reply.is_delete
     *
     * @mbggenerated
     */
    private Boolean isDelete;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column game_reply.create_time
     *
     * @mbggenerated
     */
    private Date createTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column game_reply.game_rep_id
     *
     * @return the value of game_reply.game_rep_id
     *
     * @mbggenerated
     */
    public Integer getGameRepId() {
        return gameRepId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column game_reply.game_rep_id
     *
     * @param gameRepId the value for game_reply.game_rep_id
     *
     * @mbggenerated
     */
    public void setGameRepId(Integer gameRepId) {
        this.gameRepId = gameRepId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column game_reply.player_id
     *
     * @return the value of game_reply.player_id
     *
     * @mbggenerated
     */
    public Integer getPlayerId() {
        return playerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column game_reply.player_id
     *
     * @param playerId the value for game_reply.player_id
     *
     * @mbggenerated
     */
    public void setPlayerId(Integer playerId) {
        this.playerId = playerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column game_reply.game_res_id
     *
     * @return the value of game_reply.game_res_id
     *
     * @mbggenerated
     */
    public Integer getGameResId() {
        return gameResId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column game_reply.game_res_id
     *
     * @param gameResId the value for game_reply.game_res_id
     *
     * @mbggenerated
     */
    public void setGameResId(Integer gameResId) {
        this.gameResId = gameResId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column game_reply.status
     *
     * @return the value of game_reply.status
     *
     * @mbggenerated
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column game_reply.status
     *
     * @param status the value for game_reply.status
     *
     * @mbggenerated
     */
    public void setStatus(String status) {
        this.status = status == null ? null : status.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column game_reply.note
     *
     * @return the value of game_reply.note
     *
     * @mbggenerated
     */
    public String getNote() {
        return note;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column game_reply.note
     *
     * @param note the value for game_reply.note
     *
     * @mbggenerated
     */
    public void setNote(String note) {
        this.note = note == null ? null : note.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column game_reply.is_delete
     *
     * @return the value of game_reply.is_delete
     *
     * @mbggenerated
     */
    public Boolean getIsDelete() {
        return isDelete;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column game_reply.is_delete
     *
     * @param isDelete the value for game_reply.is_delete
     *
     * @mbggenerated
     */
    public void setIsDelete(Boolean isDelete) {
        this.isDelete = isDelete;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column game_reply.create_time
     *
     * @return the value of game_reply.create_time
     *
     * @mbggenerated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column game_reply.create_time
     *
     * @param createTime the value for game_reply.create_time
     *
     * @mbggenerated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }
}