package zhentao.zhang.pojo;

import java.util.Date;

public class Player {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column player.player_id
     *
     * @mbggenerated
     */
    private Integer playerId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column player.user_id
     *
     * @mbggenerated
     */
    private Integer userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column player.start_play_time
     *
     * @mbggenerated
     */
    private Date startPlayTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column player.team
     *
     * @mbggenerated
     */
    private String team;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column player.experience
     *
     * @mbggenerated
     */
    private String experience;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column player.honor
     *
     * @mbggenerated
     */
    private String honor;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column player.register_time
     *
     * @mbggenerated
     */
    private Date registerTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column player.note
     *
     * @mbggenerated
     */
    private String note;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column player.is_delete
     *
     * @mbggenerated
     */
    private Boolean isDelete;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column player.other
     *
     * @mbggenerated
     */
    private String other;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column player.player_id
     *
     * @return the value of player.player_id
     *
     * @mbggenerated
     */
    public Integer getPlayerId() {
        return playerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column player.player_id
     *
     * @param playerId the value for player.player_id
     *
     * @mbggenerated
     */
    public void setPlayerId(Integer playerId) {
        this.playerId = playerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column player.user_id
     *
     * @return the value of player.user_id
     *
     * @mbggenerated
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column player.user_id
     *
     * @param userId the value for player.user_id
     *
     * @mbggenerated
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column player.start_play_time
     *
     * @return the value of player.start_play_time
     *
     * @mbggenerated
     */
    public Date getStartPlayTime() {
        return startPlayTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column player.start_play_time
     *
     * @param startPlayTime the value for player.start_play_time
     *
     * @mbggenerated
     */
    public void setStartPlayTime(Date startPlayTime) {
        this.startPlayTime = startPlayTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column player.team
     *
     * @return the value of player.team
     *
     * @mbggenerated
     */
    public String getTeam() {
        return team;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column player.team
     *
     * @param team the value for player.team
     *
     * @mbggenerated
     */
    public void setTeam(String team) {
        this.team = team == null ? null : team.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column player.experience
     *
     * @return the value of player.experience
     *
     * @mbggenerated
     */
    public String getExperience() {
        return experience;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column player.experience
     *
     * @param experience the value for player.experience
     *
     * @mbggenerated
     */
    public void setExperience(String experience) {
        this.experience = experience == null ? null : experience.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column player.honor
     *
     * @return the value of player.honor
     *
     * @mbggenerated
     */
    public String getHonor() {
        return honor;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column player.honor
     *
     * @param honor the value for player.honor
     *
     * @mbggenerated
     */
    public void setHonor(String honor) {
        this.honor = honor == null ? null : honor.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column player.register_time
     *
     * @return the value of player.register_time
     *
     * @mbggenerated
     */
    public Date getRegisterTime() {
        return registerTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column player.register_time
     *
     * @param registerTime the value for player.register_time
     *
     * @mbggenerated
     */
    public void setRegisterTime(Date registerTime) {
        this.registerTime = registerTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column player.note
     *
     * @return the value of player.note
     *
     * @mbggenerated
     */
    public String getNote() {
        return note;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column player.note
     *
     * @param note the value for player.note
     *
     * @mbggenerated
     */
    public void setNote(String note) {
        this.note = note == null ? null : note.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column player.is_delete
     *
     * @return the value of player.is_delete
     *
     * @mbggenerated
     */
    public Boolean getIsDelete() {
        return isDelete;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column player.is_delete
     *
     * @param isDelete the value for player.is_delete
     *
     * @mbggenerated
     */
    public void setIsDelete(Boolean isDelete) {
        this.isDelete = isDelete;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column player.other
     *
     * @return the value of player.other
     *
     * @mbggenerated
     */
    public String getOther() {
        return other;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column player.other
     *
     * @param other the value for player.other
     *
     * @mbggenerated
     */
    public void setOther(String other) {
        this.other = other == null ? null : other.trim();
    }
}