package zhentao.zhang.pojo;

import java.util.Date;

public class RefereeReservation {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column referee_reservation.ref_res_id
     *
     * @mbggenerated
     */
    private Integer refResId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column referee_reservation.player_id
     *
     * @mbggenerated
     */
    private Integer playerId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column referee_reservation.game_time
     *
     * @mbggenerated
     */
    private Date gameTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column referee_reservation.address
     *
     * @mbggenerated
     */
    private String address;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column referee_reservation.game_state
     *
     * @mbggenerated
     */
    private String gameState;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column referee_reservation.referee_count
     *
     * @mbggenerated
     */
    private String refereeCount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column referee_reservation.referee_require
     *
     * @mbggenerated
     */
    private String refereeRequire;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column referee_reservation.reward
     *
     * @mbggenerated
     */
    private String reward;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column referee_reservation.note
     *
     * @mbggenerated
     */
    private String note;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column referee_reservation.is_receive
     *
     * @mbggenerated
     */
    private Boolean isReceive;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column referee_reservation.is_delete
     *
     * @mbggenerated
     */
    private Boolean isDelete;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column referee_reservation.create_time
     *
     * @mbggenerated
     */
    private Date createTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column referee_reservation.ref_res_id
     *
     * @return the value of referee_reservation.ref_res_id
     *
     * @mbggenerated
     */
    public Integer getRefResId() {
        return refResId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column referee_reservation.ref_res_id
     *
     * @param refResId the value for referee_reservation.ref_res_id
     *
     * @mbggenerated
     */
    public void setRefResId(Integer refResId) {
        this.refResId = refResId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column referee_reservation.player_id
     *
     * @return the value of referee_reservation.player_id
     *
     * @mbggenerated
     */
    public Integer getPlayerId() {
        return playerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column referee_reservation.player_id
     *
     * @param playerId the value for referee_reservation.player_id
     *
     * @mbggenerated
     */
    public void setPlayerId(Integer playerId) {
        this.playerId = playerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column referee_reservation.game_time
     *
     * @return the value of referee_reservation.game_time
     *
     * @mbggenerated
     */
    public Date getGameTime() {
        return gameTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column referee_reservation.game_time
     *
     * @param gameTime the value for referee_reservation.game_time
     *
     * @mbggenerated
     */
    public void setGameTime(Date gameTime) {
        this.gameTime = gameTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column referee_reservation.address
     *
     * @return the value of referee_reservation.address
     *
     * @mbggenerated
     */
    public String getAddress() {
        return address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column referee_reservation.address
     *
     * @param address the value for referee_reservation.address
     *
     * @mbggenerated
     */
    public void setAddress(String address) {
        this.address = address == null ? null : address.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column referee_reservation.game_state
     *
     * @return the value of referee_reservation.game_state
     *
     * @mbggenerated
     */
    public String getGameState() {
        return gameState;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column referee_reservation.game_state
     *
     * @param gameState the value for referee_reservation.game_state
     *
     * @mbggenerated
     */
    public void setGameState(String gameState) {
        this.gameState = gameState == null ? null : gameState.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column referee_reservation.referee_count
     *
     * @return the value of referee_reservation.referee_count
     *
     * @mbggenerated
     */
    public String getRefereeCount() {
        return refereeCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column referee_reservation.referee_count
     *
     * @param refereeCount the value for referee_reservation.referee_count
     *
     * @mbggenerated
     */
    public void setRefereeCount(String refereeCount) {
        this.refereeCount = refereeCount == null ? null : refereeCount.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column referee_reservation.referee_require
     *
     * @return the value of referee_reservation.referee_require
     *
     * @mbggenerated
     */
    public String getRefereeRequire() {
        return refereeRequire;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column referee_reservation.referee_require
     *
     * @param refereeRequire the value for referee_reservation.referee_require
     *
     * @mbggenerated
     */
    public void setRefereeRequire(String refereeRequire) {
        this.refereeRequire = refereeRequire == null ? null : refereeRequire.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column referee_reservation.reward
     *
     * @return the value of referee_reservation.reward
     *
     * @mbggenerated
     */
    public String getReward() {
        return reward;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column referee_reservation.reward
     *
     * @param reward the value for referee_reservation.reward
     *
     * @mbggenerated
     */
    public void setReward(String reward) {
        this.reward = reward == null ? null : reward.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column referee_reservation.note
     *
     * @return the value of referee_reservation.note
     *
     * @mbggenerated
     */
    public String getNote() {
        return note;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column referee_reservation.note
     *
     * @param note the value for referee_reservation.note
     *
     * @mbggenerated
     */
    public void setNote(String note) {
        this.note = note == null ? null : note.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column referee_reservation.is_receive
     *
     * @return the value of referee_reservation.is_receive
     *
     * @mbggenerated
     */
    public Boolean getIsReceive() {
        return isReceive;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column referee_reservation.is_receive
     *
     * @param isReceive the value for referee_reservation.is_receive
     *
     * @mbggenerated
     */
    public void setIsReceive(Boolean isReceive) {
        this.isReceive = isReceive;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column referee_reservation.is_delete
     *
     * @return the value of referee_reservation.is_delete
     *
     * @mbggenerated
     */
    public Boolean getIsDelete() {
        return isDelete;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column referee_reservation.is_delete
     *
     * @param isDelete the value for referee_reservation.is_delete
     *
     * @mbggenerated
     */
    public void setIsDelete(Boolean isDelete) {
        this.isDelete = isDelete;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column referee_reservation.create_time
     *
     * @return the value of referee_reservation.create_time
     *
     * @mbggenerated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column referee_reservation.create_time
     *
     * @param createTime the value for referee_reservation.create_time
     *
     * @mbggenerated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }
}