package zhentao.zhang.pojo;

import java.util.Date;

public class Referee {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column referee.referee_id
     *
     * @mbggenerated
     */
    private Integer refereeId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column referee.user_id
     *
     * @mbggenerated
     */
    private Integer userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column referee.start_judge_time
     *
     * @mbggenerated
     */
    private Date startJudgeTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column referee.experience
     *
     * @mbggenerated
     */
    private String experience;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column referee.honor
     *
     * @mbggenerated
     */
    private String honor;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column referee.certificate
     *
     * @mbggenerated
     */
    private String certificate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column referee.register_time
     *
     * @mbggenerated
     */
    private Date registerTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column referee.note
     *
     * @mbggenerated
     */
    private String note;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column referee.is_delete
     *
     * @mbggenerated
     */
    private Boolean isDelete;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column referee.other
     *
     * @mbggenerated
     */
    private String other;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column referee.referee_id
     *
     * @return the value of referee.referee_id
     *
     * @mbggenerated
     */
    public Integer getRefereeId() {
        return refereeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column referee.referee_id
     *
     * @param refereeId the value for referee.referee_id
     *
     * @mbggenerated
     */
    public void setRefereeId(Integer refereeId) {
        this.refereeId = refereeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column referee.user_id
     *
     * @return the value of referee.user_id
     *
     * @mbggenerated
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column referee.user_id
     *
     * @param userId the value for referee.user_id
     *
     * @mbggenerated
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column referee.start_judge_time
     *
     * @return the value of referee.start_judge_time
     *
     * @mbggenerated
     */
    public Date getStartJudgeTime() {
        return startJudgeTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column referee.start_judge_time
     *
     * @param startJudgeTime the value for referee.start_judge_time
     *
     * @mbggenerated
     */
    public void setStartJudgeTime(Date startJudgeTime) {
        this.startJudgeTime = startJudgeTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column referee.experience
     *
     * @return the value of referee.experience
     *
     * @mbggenerated
     */
    public String getExperience() {
        return experience;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column referee.experience
     *
     * @param experience the value for referee.experience
     *
     * @mbggenerated
     */
    public void setExperience(String experience) {
        this.experience = experience == null ? null : experience.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column referee.honor
     *
     * @return the value of referee.honor
     *
     * @mbggenerated
     */
    public String getHonor() {
        return honor;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column referee.honor
     *
     * @param honor the value for referee.honor
     *
     * @mbggenerated
     */
    public void setHonor(String honor) {
        this.honor = honor == null ? null : honor.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column referee.certificate
     *
     * @return the value of referee.certificate
     *
     * @mbggenerated
     */
    public String getCertificate() {
        return certificate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column referee.certificate
     *
     * @param certificate the value for referee.certificate
     *
     * @mbggenerated
     */
    public void setCertificate(String certificate) {
        this.certificate = certificate == null ? null : certificate.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column referee.register_time
     *
     * @return the value of referee.register_time
     *
     * @mbggenerated
     */
    public Date getRegisterTime() {
        return registerTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column referee.register_time
     *
     * @param registerTime the value for referee.register_time
     *
     * @mbggenerated
     */
    public void setRegisterTime(Date registerTime) {
        this.registerTime = registerTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column referee.note
     *
     * @return the value of referee.note
     *
     * @mbggenerated
     */
    public String getNote() {
        return note;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column referee.note
     *
     * @param note the value for referee.note
     *
     * @mbggenerated
     */
    public void setNote(String note) {
        this.note = note == null ? null : note.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column referee.is_delete
     *
     * @return the value of referee.is_delete
     *
     * @mbggenerated
     */
    public Boolean getIsDelete() {
        return isDelete;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column referee.is_delete
     *
     * @param isDelete the value for referee.is_delete
     *
     * @mbggenerated
     */
    public void setIsDelete(Boolean isDelete) {
        this.isDelete = isDelete;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column referee.other
     *
     * @return the value of referee.other
     *
     * @mbggenerated
     */
    public String getOther() {
        return other;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column referee.other
     *
     * @param other the value for referee.other
     *
     * @mbggenerated
     */
    public void setOther(String other) {
        this.other = other == null ? null : other.trim();
    }
}