package zhentao.zhang.dao;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import zhentao.zhang.pojo.GameReply;
import zhentao.zhang.pojo.GameReplyExample;

public interface GameReplyMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table game_reply
     *
     * @mbggenerated
     */
    int countByExample(GameReplyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table game_reply
     *
     * @mbggenerated
     */
    int deleteByExample(GameReplyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table game_reply
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer gameRepId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table game_reply
     *
     * @mbggenerated
     */
    int insert(GameReply record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table game_reply
     *
     * @mbggenerated
     */
    int insertSelective(GameReply record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table game_reply
     *
     * @mbggenerated
     */
    List<GameReply> selectByExample(GameReplyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table game_reply
     *
     * @mbggenerated
     */
    GameReply selectByPrimaryKey(Integer gameRepId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table game_reply
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") GameReply record, @Param("example") GameReplyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table game_reply
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") GameReply record, @Param("example") GameReplyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table game_reply
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(GameReply record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table game_reply
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(GameReply record);
}