package zhentao.zhang.dao;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import zhentao.zhang.pojo.Player;
import zhentao.zhang.pojo.PlayerExample;

public interface PlayerMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table player
     *
     * @mbggenerated
     */
    int countByExample(PlayerExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table player
     *
     * @mbggenerated
     */
    int deleteByExample(PlayerExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table player
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer playerId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table player
     *
     * @mbggenerated
     */
    int insert(Player record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table player
     *
     * @mbggenerated
     */
    int insertSelective(Player record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table player
     *
     * @mbggenerated
     */
    List<Player> selectByExample(PlayerExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table player
     *
     * @mbggenerated
     */
    Player selectByPrimaryKey(Integer playerId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table player
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") Player record, @Param("example") PlayerExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table player
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") Player record, @Param("example") PlayerExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table player
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(Player record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table player
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(Player record);
}